INSERT INTO [dbo].[T_WorkflowHistory]
           ([WorkflowControlNo]
           ,[HistoryNo]
           ,[WfPositionId]
           ,[WorkflowNo]
           ,[FromUserId]
           ,[FromUserInfo]
           ,[ActionType]
           ,[ToUserId]
           ,[ToUserInfo]
           ,[ToUserPositionTitlesId]
           ,[NextWfPositionId]
           ,[NextWorkflowNo]
           ,[ReserveArea]
           ,[ReplyDeadline]
           ,[StartDate]
           ,[AcceptanceDate]
           ,[AcceptanceUserId]
           ,[AcceptanceUserInfo]
           ,[EndDate])

SELECT [WorkflowControlNo]
      ,[HistoryNo]
      ,[WfPositionId]
      ,[WorkflowNo]
      ,[FromUserId]
      ,[FromUserInfo]
      ,[ActionType]
      ,[ToUserId]
      ,[ToUserInfo]
      ,[ToUserPositionTitlesId]
      ,[NextWfPositionId]
      ,[NextWorkflowNo]
      ,[ReserveArea]
      ,[ReplyDeadline]
      ,[StartDate]
      ,[AcceptanceDate]
      ,[AcceptanceUserId]
      ,[AcceptanceUserInfo]
	  ,GETDATE() 
  FROM [dbo].[T_CurrentWorkflow]


