'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Aspx_testScreenCtrl_WebForm4

    '''<summary>
    '''btnButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton1 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton2 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton3 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton4 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton5 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''CheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox1 As Global.Touryo.Infrastructure.CustomControl.WebCustomCheckBox

    '''<summary>
    '''btnButton6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton6 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton7 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton8 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton9 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton10 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton11 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton12 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton13 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton14 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton15 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton16 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton17 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton18 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton19 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton20 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton21 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton22 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton23 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton24 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton25 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton26 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.Touryo.Infrastructure.CustomControl.WebCustomTextBox

    '''<summary>
    '''btnButton27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton27 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''btnButton28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnButton28 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image
End Class
