//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPQuery_Tool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPQuery_Tool.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app.Config parameter has not been set. :.
        /// </summary>
        internal static string AppConfigParameterNotSet {
            get {
                return ResourceManager.GetString("AppConfigParameterNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Error is :.
        /// </summary>
        internal static string CheckExceptionError {
            get {
                return ResourceManager.GetString("CheckExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing process.
        /// </summary>
        internal static string ClosingProcess {
            get {
                return ResourceManager.GetString("ClosingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry point : {0}.
        /// </summary>
        internal static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape character was not set..
        /// </summary>
        internal static string EscCharacterNotSet {
            get {
                return ResourceManager.GetString("EscCharacterNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data tier definition information file format error : There was no table name..
        /// </summary>
        internal static string FileFormatError {
            get {
                return ResourceManager.GetString("FileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Generation Completed !.
        /// </summary>
        internal static string FileGenComplete {
            get {
                return ResourceManager.GetString("FileGenComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check error: Database type information file [{0}] does not exist..
        /// </summary>
        internal static string FilenotExistDBtypeInfo {
            get {
                return ResourceManager.GetString("FilenotExistDBtypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check error: Data tier definition information file [{0}] does not exist..
        /// </summary>
        internal static string FilenotExistDlayerInfo {
            get {
                return ResourceManager.GetString("FilenotExistDlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check error:. NET type information file [{0}] does not exist..
        /// </summary>
        internal static string FilenotExistNETtypeInfo {
            get {
                return ResourceManager.GetString("FilenotExistNETtypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder of the input file (template file) does not exist..
        /// </summary>
        internal static string InputFileRootFolderNotExist {
            get {
                return ResourceManager.GetString("InputFileRootFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Format.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;[Log output text]&quot;.
        /// </summary>
        internal static string LogOutputText {
            get {
                return ResourceManager.GetString("LogOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no saved configuration file..
        /// </summary>
        internal static string MSG_CONFIG_FILE_NOT_EXIST {
            get {
                return ResourceManager.GetString("MSG_CONFIG_FILE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic parameterized query was executed..
        /// </summary>
        internal static string MSG_EXEC_DQP {
            get {
                return ResourceManager.GetString("MSG_EXEC_DQP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static parameterized query was executed..
        /// </summary>
        internal static string MSG_EXEC_SPQ {
            get {
                return ResourceManager.GetString("MSG_EXEC_SPQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the IP address of the database server.
        /// </summary>
        internal static string MSG_INPUT_IP {
            get {
                return ResourceManager.GetString("MSG_INPUT_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the login account to the database: Password.
        /// </summary>
        internal static string MSG_INPUT_PWD {
            get {
                return ResourceManager.GetString("MSG_INPUT_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the login account to the database: User ID.
        /// </summary>
        internal static string MSG_INPUT_UID {
            get {
                return ResourceManager.GetString("MSG_INPUT_UID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save this query file?.
        /// </summary>
        internal static string MSG_IS_QUERY_FILE_SAVED {
            get {
                return ResourceManager.GetString("MSG_IS_QUERY_FILE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no columns available to generate screens..
        /// </summary>
        internal static string Nocolumns {
            get {
                return ResourceManager.GetString("Nocolumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no time stamp column name..
        /// </summary>
        internal static string NoTimestampColName {
            get {
                return ResourceManager.GetString("NoTimestampColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file (*.csv)|*.csv.
        /// </summary>
        internal static string OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data tier definition information file..
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder (Dao class file, SQL file. Etc) of the output file does not exist..
        /// </summary>
        internal static string OutputFileRootFolderNotExist {
            get {
                return ResourceManager.GetString("OutputFileRootFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the root folder path (Dao file, SQL file) of the output file.
        /// </summary>
        internal static string OutputFolderPath {
            get {
                return ResourceManager.GetString("OutputFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Performance information - execution process].
        /// </summary>
        internal static string PerformanceExecution {
            get {
                return ResourceManager.GetString("PerformanceExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Keys were not set to the table :.
        /// </summary>
        internal static string PKnotAvailable {
            get {
                return ResourceManager.GetString("PKnotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check Primary Keys were set to the Table or not..
        /// </summary>
        internal static string PkSetMessgae {
            get {
                return ResourceManager.GetString("PkSetMessgae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key was not defined in the table..
        /// </summary>
        internal static string PrimaryKeyNotDefined {
            get {
                return ResourceManager.GetString("PrimaryKeyNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run from a file.
        /// </summary>
        internal static string RunFile {
            get {
                return ResourceManager.GetString("RunFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run from TextBox.
        /// </summary>
        internal static string RunTextBox {
            get {
                return ResourceManager.GetString("RunTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a run-time error : {0}.
        /// </summary>
        internal static string RuntimeError {
            get {
                return ResourceManager.GetString("RuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screens were generated automatically..
        /// </summary>
        internal static string ScreenGenerationSuccess {
            get {
                return ResourceManager.GetString("ScreenGenerationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic control (Ran with auto-commit transaction mode.).
        /// </summary>
        internal static string STATUS_AUTO_MODE_WAS_SELECTED {
            get {
                return ResourceManager.GetString("STATUS_AUTO_MODE_WAS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured connection setting was loaded..
        /// </summary>
        internal static string STATUS_CONFIGURATION_LOADED {
            get {
                return ResourceManager.GetString("STATUS_CONFIGURATION_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured connection setting was saved..
        /// </summary>
        internal static string STATUS_CONFIGURATION_SAVED {
            get {
                return ResourceManager.GetString("STATUS_CONFIGURATION_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection was closed..
        /// </summary>
        internal static string STATUS_CONNECTION_CLOSED {
            get {
                return ResourceManager.GetString("STATUS_CONNECTION_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection was opened..
        /// </summary>
        internal static string STATUS_CONNECTION_OPENED {
            get {
                return ResourceManager.GetString("STATUS_CONNECTION_OPENED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured a new connection string setting..
        /// </summary>
        internal static string STATUS_CREATE_CONFIGURATION {
            get {
                return ResourceManager.GetString("STATUS_CREATE_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} data provider was selected..
        /// </summary>
        internal static string STATUS_DATA_PROVIDER_SELECTED {
            get {
                return ResourceManager.GetString("STATUS_DATA_PROVIDER_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial state.
        /// </summary>
        internal static string STATUS_INIT {
            get {
                return ResourceManager.GetString("STATUS_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual control (Manually control the transaction using this button.).
        /// </summary>
        internal static string STATUS_MANUAL_MODE_WAS_SELECTED {
            get {
                return ResourceManager.GetString("STATUS_MANUAL_MODE_WAS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was canceled..
        /// </summary>
        internal static string STATUS_PROC_CANCELED {
            get {
                return ResourceManager.GetString("STATUS_PROC_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query was executed..
        /// </summary>
        internal static string STATUS_QUERY_EXECED {
            get {
                return ResourceManager.GetString("STATUS_QUERY_EXECED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query file was closed..
        /// </summary>
        internal static string STATUS_QUERY_FILE_CLOSED {
            get {
                return ResourceManager.GetString("STATUS_QUERY_FILE_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query file was opened..
        /// </summary>
        internal static string STATUS_QUERY_FILE_OPENED {
            get {
                return ResourceManager.GetString("STATUS_QUERY_FILE_OPENED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified query was saved to the query file..
        /// </summary>
        internal static string STATUS_QUERY_FILE_OVERWRITED {
            get {
                return ResourceManager.GetString("STATUS_QUERY_FILE_OVERWRITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query has been saved to a new query file..
        /// </summary>
        internal static string STATUS_QUERY_FILE_SAVED {
            get {
                return ResourceManager.GetString("STATUS_QUERY_FILE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction was committed..
        /// </summary>
        internal static string STATUS_TRANSACTION_COMMITED {
            get {
                return ResourceManager.GetString("STATUS_TRANSACTION_COMMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction was rolled back..
        /// </summary>
        internal static string STATUS_TRANSACTION_ROLLBACKED {
            get {
                return ResourceManager.GetString("STATUS_TRANSACTION_ROLLBACKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction was started..
        /// </summary>
        internal static string STATUS_TRANSACTION_STARTED {
            get {
                return ResourceManager.GetString("STATUS_TRANSACTION_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before [{0}], only indent can be specified. : {1}.
        /// </summary>
        internal static string StringIndentation {
            get {
                return ResourceManager.GetString("StringIndentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file does not exist. :.
        /// </summary>
        internal static string TempFilenotExists {
            get {
                return ResourceManager.GetString("TempFilenotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the root folder path of the input file (template file)..
        /// </summary>
        internal static string TemplateFolderPath {
            get {
                return ResourceManager.GetString("TemplateFolderPath", resourceCulture);
            }
        }
    }
}
