SELECT * FROM ADMINISTRATOR.EMPLOYEE
WHERE
EMPNO IN (SELECT EMPNO FROM ADMINISTRATOR.EMPLOYEE)
AND SEX IN (@PLIST1, @PLIST2)
ORDER BY %COLUMN% %SEQUENCE%

/*PARAM* PLIST1, Char, M *PARAM*/
/*PARAM* PLIST2, Char, F *PARAM*/
/*PARAM*COLUMN,EMPNO*PARAM*/
/*PARAM*SEQUENCE,DESC*PARAM*/

-- パラメタ設定済み
