//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectX_sample.Aspx.testFxLayerP.nest {
    
    
    public partial class testScreen1nest {
        
        /// <summary>
        /// btnButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomButton btnButton1;
        
        /// <summary>
        /// lbnLinkButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomLinkButton lbnLinkButton1;
        
        /// <summary>
        /// ibnImageButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageButton ibnImageButton1;
        
        /// <summary>
        /// impImageMap1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageMap impImageMap1;
        
        /// <summary>
        /// btnButton2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomButton btnButton2;
        
        /// <summary>
        /// lbnLinkButton2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomLinkButton lbnLinkButton2;
        
        /// <summary>
        /// ibnImageButton2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageButton ibnImageButton2;
        
        /// <summary>
        /// impImageMap2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageMap impImageMap2;
        
        /// <summary>
        /// TextBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomTextBox TextBox1;
        
        /// <summary>
        /// btnButton3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomButton btnButton3;
        
        /// <summary>
        /// lbnLinkButton3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomLinkButton lbnLinkButton3;
        
        /// <summary>
        /// ibnImageButton3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageButton ibnImageButton3;
        
        /// <summary>
        /// CheckBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomCheckBox CheckBox1;
        
        /// <summary>
        /// TextBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomTextBox TextBox2;
        
        /// <summary>
        /// CheckBox1a control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomCheckBox CheckBox1a;
        
        /// <summary>
        /// TextBox2a control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomTextBox TextBox2a;
        
        /// <summary>
        /// TextBox3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomTextBox TextBox3;
        
        /// <summary>
        /// btnButton4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomButton btnButton4;
        
        /// <summary>
        /// lbnLinkButton4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomLinkButton lbnLinkButton4;
        
        /// <summary>
        /// ibnImageButton4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageButton ibnImageButton4;
        
        /// <summary>
        /// impImageMap4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageMap impImageMap4;
        
        /// <summary>
        /// TextBox4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomTextBox TextBox4;
        
        /// <summary>
        /// btnButton21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomButton btnButton21;
        
        /// <summary>
        /// lbnLinkButton21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomLinkButton lbnLinkButton21;
        
        /// <summary>
        /// ibnImageButton21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageButton ibnImageButton21;
        
        /// <summary>
        /// impImageMap21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageMap impImageMap21;
        
        /// <summary>
        /// btnButton22 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomButton btnButton22;
        
        /// <summary>
        /// lbnLinkButton22 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomLinkButton lbnLinkButton22;
        
        /// <summary>
        /// ibnImageButton22 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageButton ibnImageButton22;
        
        /// <summary>
        /// impImageMap22 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageMap impImageMap22;
        
        /// <summary>
        /// btnButton23 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomButton btnButton23;
        
        /// <summary>
        /// lbnLinkButton23 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomLinkButton lbnLinkButton23;
        
        /// <summary>
        /// ibnImageButton23 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageButton ibnImageButton23;
        
        /// <summary>
        /// impImageMap23 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageMap impImageMap23;
        
        /// <summary>
        /// btnButton24 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomButton btnButton24;
        
        /// <summary>
        /// lbnLinkButton24 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomLinkButton lbnLinkButton24;
        
        /// <summary>
        /// ibnImageButton24 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageButton ibnImageButton24;
        
        /// <summary>
        /// TextBox5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomTextBox TextBox5;
        
        /// <summary>
        /// btnButton31 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomButton btnButton31;
        
        /// <summary>
        /// lbnLinkButton31 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomLinkButton lbnLinkButton31;
        
        /// <summary>
        /// ibnImageButton31 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageButton ibnImageButton31;
        
        /// <summary>
        /// impImageMap31 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageMap impImageMap31;
        
        /// <summary>
        /// btnButton32 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomButton btnButton32;
        
        /// <summary>
        /// lbnLinkButton32 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomLinkButton lbnLinkButton32;
        
        /// <summary>
        /// ibnImageButton32 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageButton ibnImageButton32;
        
        /// <summary>
        /// impImageMap32 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageMap impImageMap32;
        
        /// <summary>
        /// btnButton33 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomButton btnButton33;
        
        /// <summary>
        /// lbnLinkButton33 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomLinkButton lbnLinkButton33;
        
        /// <summary>
        /// ibnImageButton33 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageButton ibnImageButton33;
        
        /// <summary>
        /// impImageMap33 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Touryo.Infrastructure.CustomControl.WebCustomImageMap impImageMap33;
    }
}
