//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoGen_Tool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaoGen_Tool.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app.Config parameter has not been set. :.
        /// </summary>
        internal static string AppConfigParameterNotSet {
            get {
                return ResourceManager.GetString("AppConfigParameterNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Error is :.
        /// </summary>
        internal static string CheckExceptionError {
            get {
                return ResourceManager.GetString("CheckExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape character is not set..
        /// </summary>
        internal static string EscCharacterNotSet {
            get {
                return ResourceManager.GetString("EscCharacterNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D layer definition information file format error : There is no table name..
        /// </summary>
        internal static string FileFormatError {
            get {
                return ResourceManager.GetString("FileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Generation Completed !.
        /// </summary>
        internal static string FileGenComplete {
            get {
                return ResourceManager.GetString("FileGenComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check error: file type information DB [{0}] does not exist..
        /// </summary>
        internal static string FilenotExistDBtypeInfo {
            get {
                return ResourceManager.GetString("FilenotExistDBtypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check error:Defined D layer Information file  defined  [{0}] does not exist..
        /// </summary>
        internal static string FilenotExistDlayerInfo {
            get {
                return ResourceManager.GetString("FilenotExistDlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check error:. NET type information file [{0}] does not exist..
        /// </summary>
        internal static string FilenotExistNETtypeInfo {
            get {
                return ResourceManager.GetString("FilenotExistNETtypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder of the input file (template file) does not exist..
        /// </summary>
        internal static string InputFileRootFolderNotExist {
            get {
                return ResourceManager.GetString("InputFileRootFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Format.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no time stamp column name..
        /// </summary>
        internal static string NoTimestampColName {
            get {
                return ResourceManager.GetString("NoTimestampColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file (*.csv)|*.csv.
        /// </summary>
        internal static string OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D layer definition information file.
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder (Dao class file, SQL file. Etc) of the output file does not exist..
        /// </summary>
        internal static string OutputFileRootFolderNotExist {
            get {
                return ResourceManager.GetString("OutputFileRootFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the root folder path (Dao file, SQL file) of the output file.
        /// </summary>
        internal static string OutputFolderPath {
            get {
                return ResourceManager.GetString("OutputFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key is not defined in the table..
        /// </summary>
        internal static string PrimaryKeyNotDefined {
            get {
                return ResourceManager.GetString("PrimaryKeyNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a run-time error:.
        /// </summary>
        internal static string RuntimeError {
            get {
                return ResourceManager.GetString("RuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In front of, I can only be specified indent:..
        /// </summary>
        internal static string StringIndentation {
            get {
                return ResourceManager.GetString("StringIndentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file does not exist. :.
        /// </summary>
        internal static string TempFilenotExists {
            get {
                return ResourceManager.GetString("TempFilenotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the root folder path input file (template file).
        /// </summary>
        internal static string TemplateFolderPath {
            get {
                return ResourceManager.GetString("TemplateFolderPath", resourceCulture);
            }
        }
    }
}
