CREATE USER SCOTT
IDENTIFIED BY           
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
/
GRANT AQ_ADMINISTRATOR_ROLE TO SCOTT WITH ADMIN OPTION
/
GRANT CREATE MATERIALIZED VIEW TO SCOTT
/
GRANT CREATE SEQUENCE TO SCOTT
/
GRANT CREATE SESSION TO SCOTT
/
GRANT CREATE TABLE TO SCOTT
/
GRANT CREATE VIEW TO SCOTT
/
GRANT GLOBAL QUERY REWRITE TO SCOTT
/
GRANT SELECT ANY TABLE TO SCOTT
/
GRANT UNLIMITED TABLESPACE TO SCOTT WITH ADMIN OPTION
/
