//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoGen_Tool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaoGen_Tool.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app.Config parameter has not been set. :.
        /// </summary>
        internal static string AppConfigParameterNotSet {
            get {
                return ResourceManager.GetString("AppConfigParameterNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not have more than one table with the same name on the same DB ( the specification for the Data layer generator for {0}) .
        /// </summary>
        internal static string CautionPrerequisite {
            get {
                return ResourceManager.GetString("CautionPrerequisite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note - ( prerequisite ) .
        /// </summary>
        internal static string CautionPrerequisiteCaption {
            get {
                return ResourceManager.GetString("CautionPrerequisiteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Is the specification of Data layer generator for Oracle ) that we only consider the table owned by the ( user ) schema [{0}].
        /// </summary>
        internal static string CautionPrerequisiteOracle {
            get {
                return ResourceManager.GetString("CautionPrerequisiteOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Error is :.
        /// </summary>
        internal static string CheckExceptionError {
            get {
                return ResourceManager.GetString("CheckExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display ({0}) dialog of schema information of DBMS.
        /// </summary>
        internal static string DisplaySchemaInfoDialogBox {
            get {
                return ResourceManager.GetString("DisplaySchemaInfoDialogBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion of generation of the Data layer definition information!.
        /// </summary>
        internal static string DlayerGeneratedMessage {
            get {
                return ResourceManager.GetString("DlayerGeneratedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Point:.
        /// </summary>
        internal static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape character is not set..
        /// </summary>
        internal static string EscCharacterNotSet {
            get {
                return ResourceManager.GetString("EscCharacterNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data layer definition information file format error : There is no table name..
        /// </summary>
        internal static string FileFormatError {
            get {
                return ResourceManager.GetString("FileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Generation Completed !.
        /// </summary>
        internal static string FileGenComplete {
            get {
                return ResourceManager.GetString("FileGenComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check error: file type information DB [{0}] does not exist..
        /// </summary>
        internal static string FilenotExistDBtypeInfo {
            get {
                return ResourceManager.GetString("FilenotExistDBtypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check error:Defined Data layer Information file  defined  [{0}] does not exist..
        /// </summary>
        internal static string FilenotExistDlayerInfo {
            get {
                return ResourceManager.GetString("FilenotExistDlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check error:. NET type information file [{0}] does not exist..
        /// </summary>
        internal static string FilenotExistNETtypeInfo {
            get {
                return ResourceManager.GetString("FilenotExistNETtypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the next table..
        /// </summary>
        internal static string GotoNextTable {
            get {
                return ResourceManager.GetString("GotoNextTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder of the input file (template file) does not exist..
        /// </summary>
        internal static string InputFileRootFolderNotExist {
            get {
                return ResourceManager.GetString("InputFileRootFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Format.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta-Data Information.
        /// </summary>
        internal static string MetadataInfo {
            get {
                return ResourceManager.GetString("MetadataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no time stamp column name..
        /// </summary>
        internal static string NoTimestampColName {
            get {
                return ResourceManager.GetString("NoTimestampColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file (*.csv)|*.csv.
        /// </summary>
        internal static string OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data layer definition information file.
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder (Dao class file, SQL file. Etc) of the output file does not exist..
        /// </summary>
        internal static string OutputFileRootFolderNotExist {
            get {
                return ResourceManager.GetString("OutputFileRootFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the root folder path (Dao file, SQL file) of the output file.
        /// </summary>
        internal static string OutputFolderPath {
            get {
                return ResourceManager.GetString("OutputFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key is not defined in the table..
        /// </summary>
        internal static string PrimaryKeyNotDefined {
            get {
                return ResourceManager.GetString("PrimaryKeyNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved Word Information.
        /// </summary>
        internal static string ReservedWordInfo {
            get {
                return ResourceManager.GetString("ReservedWordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restriction Information.
        /// </summary>
        internal static string RestrictionInfo {
            get {
                return ResourceManager.GetString("RestrictionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a run-time error:.
        /// </summary>
        internal static string RuntimeError {
            get {
                return ResourceManager.GetString("RuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file (*.csv)|*.csv.
        /// </summary>
        internal static string SaveFileDialogFilter {
            get {
                return ResourceManager.GetString("SaveFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data layer definition information file.
        /// </summary>
        internal static string SaveFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the primary key information ({0}) dialog.
        /// </summary>
        internal static string SetPrimaryKeyInfo {
            get {
                return ResourceManager.GetString("SetPrimaryKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In front of, I can only be specified indent:..
        /// </summary>
        internal static string StringIndentation {
            get {
                return ResourceManager.GetString("StringIndentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Information.
        /// </summary>
        internal static string SummaryInfo {
            get {
                return ResourceManager.GetString("SummaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name, column DB-type information.
        /// </summary>
        internal static string TableNameColDbTypeInfo {
            get {
                return ResourceManager.GetString("TableNameColDbTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name, column. NET type information -.
        /// </summary>
        internal static string TableNameColdotNetTypeInfo {
            get {
                return ResourceManager.GetString("TableNameColdotNetTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name, column information -.
        /// </summary>
        internal static string TableNameColInfo {
            get {
                return ResourceManager.GetString("TableNameColInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab 1.
        /// </summary>
        internal static string TabPage1 {
            get {
                return ResourceManager.GetString("TabPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Information.
        /// </summary>
        internal static string TabPage1ColumnInfo {
            get {
                return ResourceManager.GetString("TabPage1ColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Information.
        /// </summary>
        internal static string TabPage1SchemaInfo {
            get {
                return ResourceManager.GetString("TabPage1SchemaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Information.
        /// </summary>
        internal static string TabPage1TableInfo {
            get {
                return ResourceManager.GetString("TabPage1TableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab 2.
        /// </summary>
        internal static string TabPage2 {
            get {
                return ResourceManager.GetString("TabPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Key Information.
        /// </summary>
        internal static string TabPage2PrimarykeyInfo {
            get {
                return ResourceManager.GetString("TabPage2PrimarykeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vieux Information.
        /// </summary>
        internal static string TabPage2VieuxInfo {
            get {
                return ResourceManager.GetString("TabPage2VieuxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab 3.
        /// </summary>
        internal static string TabPage3 {
            get {
                return ResourceManager.GetString("TabPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Column Information.
        /// </summary>
        internal static string TabPage3IndexColInfo {
            get {
                return ResourceManager.GetString("TabPage3IndexColInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file does not exist. :.
        /// </summary>
        internal static string TempFilenotExists {
            get {
                return ResourceManager.GetString("TempFilenotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the root folder path input file (template file).
        /// </summary>
        internal static string TemplateFolderPath {
            get {
                return ResourceManager.GetString("TemplateFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip Text.
        /// </summary>
        internal static string ToolTipText {
            get {
                return ResourceManager.GetString("ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Information.
        /// </summary>
        internal static string TypeInfo {
            get {
                return ResourceManager.GetString("TypeInfo", resourceCulture);
            }
        }
    }
}
