//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPQuery_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPQuery_Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;![CDATA[ &lt;, &gt;, &amp; .etc ]]&gt;.
        /// </summary>
        internal static string CDATA {
            get {
                return ResourceManager.GetString("CDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- COMMENT --&gt;.
        /// </summary>
        internal static string COMMENT {
            get {
                return ResourceManager.GetString("COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*PARAM*.
        /// </summary>
        internal static string CPARAM1 {
            get {
                return ResourceManager.GetString("CPARAM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *PARAM*/.
        /// </summary>
        internal static string CPARAM2 {
            get {
                return ResourceManager.GetString("CPARAM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DECMA&gt;.
        /// </summary>
        internal static string DECMA1 {
            get {
                return ResourceManager.GetString("DECMA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/DECMA&gt;.
        /// </summary>
        internal static string DECMA2 {
            get {
                return ResourceManager.GetString("DECMA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DIV/&gt;.
        /// </summary>
        internal static string DIV {
            get {
                return ResourceManager.GetString("DIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ELSE&gt;.
        /// </summary>
        internal static string ELSE1 {
            get {
                return ResourceManager.GetString("ELSE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/ELSE&gt;.
        /// </summary>
        internal static string ELSE2 {
            get {
                return ResourceManager.GetString("ELSE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;IF&gt;.
        /// </summary>
        internal static string IF1 {
            get {
                return ResourceManager.GetString("IF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/IF&gt;.
        /// </summary>
        internal static string IF2 {
            get {
                return ResourceManager.GetString("IF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;IF name=&quot;xxx&quot;&gt;.
        /// </summary>
        internal static string IF3 {
            get {
                return ResourceManager.GetString("IF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;JOIN name=&quot;xxx&quot;&gt;.
        /// </summary>
        internal static string JOIN1 {
            get {
                return ResourceManager.GetString("JOIN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/JOIN&gt;.
        /// </summary>
        internal static string JOIN2 {
            get {
                return ResourceManager.GetString("JOIN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LIST&gt;.
        /// </summary>
        internal static string LIST1 {
            get {
                return ResourceManager.GetString("LIST1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/LIST&gt;.
        /// </summary>
        internal static string LIST2 {
            get {
                return ResourceManager.GetString("LIST2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PARAM&gt;.
        /// </summary>
        internal static string PARAM1 {
            get {
                return ResourceManager.GetString("PARAM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/PARAM&gt;.
        /// </summary>
        internal static string PARAM2 {
            get {
                return ResourceManager.GetString("PARAM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ROOT&gt;.
        /// </summary>
        internal static string ROOT1 {
            get {
                return ResourceManager.GetString("ROOT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/ROOT&gt;.
        /// </summary>
        internal static string ROOT2 {
            get {
                return ResourceManager.GetString("ROOT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ROOT&gt;
        ///  SELECT * FROM XXX
        ///  &lt;WHERE&gt;
        ///    WHERE
        ///      &lt;LIST&gt;YYY IN (@p1)&lt;/LIST&gt;
        ///      &lt;IF&gt;AND ZZZ = @p2&lt;ELSE&gt;IS NULL&lt;/ELSE&gt;&lt;/IF&gt;
        ///  &lt;/WHERE&gt;
        ///  &lt;PARAM&gt;
        ///    p1, Int32, 1, 2&lt;DIV/&gt;
        ///    p2, String, xxxxxxxxxx
        ///  &lt;/PARAM&gt;
        ///&lt;/ROOT&gt;.
        /// </summary>
        internal static string SAMPLE {
            get {
                return ResourceManager.GetString("SAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SELECT name=&quot;xxx&quot;&gt;&lt;CASE value=&quot;A&quot;&gt;aaa&lt;/CASE&gt;&lt;CASE value=&quot;B&quot;&gt;bbb&lt;/CASE&gt;&lt;DEFAULT&gt;ccc&lt;/DEFAULT&gt;&lt;/SELECT&gt;.
        /// </summary>
        internal static string SELECT_CASE {
            get {
                return ResourceManager.GetString("SELECT_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SUB name=&quot;xxx&quot;&gt;.
        /// </summary>
        internal static string SUB1 {
            get {
                return ResourceManager.GetString("SUB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/SUB&gt;.
        /// </summary>
        internal static string SUB2 {
            get {
                return ResourceManager.GetString("SUB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ROOT&gt;
        ///  SELECT * FROM XXX
        ///  &lt;WHERE&gt;
        ///    WHERE
        ///      &lt;IF&gt;&lt;ELSE&gt;IS NULL&lt;/ELSE&gt;&lt;/IF&gt;
        ///  &lt;/WHERE&gt;
        ///  &lt;PARAM&gt;
        ///  &lt;/PARAM&gt;
        ///&lt;/ROOT&gt;.
        /// </summary>
        internal static string TEMPLATE {
            get {
                return ResourceManager.GetString("TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;VAL name=&quot;xxx&quot;/&gt;.
        /// </summary>
        internal static string VAL {
            get {
                return ResourceManager.GetString("VAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;WHERE&gt;.
        /// </summary>
        internal static string WHERE1 {
            get {
                return ResourceManager.GetString("WHERE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/WHERE&gt;.
        /// </summary>
        internal static string WHERE2 {
            get {
                return ResourceManager.GetString("WHERE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;.
        /// </summary>
        internal static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
    }
}
