//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18408
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touryo.Infrastructure.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrameworkExceptionMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrameworkExceptionMessageResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Touryo.Infrastructure.Framework.Resources.FrameworkExceptionMessageResource", typeof(FrameworkExceptionMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The call-back corresponding to event classification is inaccurate (null or inaccurate type). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ASYNC_EVENT_ENTRY_CALLBACK_CHECK_ERROR {
            get {
                return ResourceManager.GetString("ASYNC_EVENT_ENTRY_CALLBACK_CHECK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   event classification is inaccurate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ASYNC_EVENT_ENTRY_CHECK_ERROR {
            get {
                return ResourceManager.GetString("ASYNC_EVENT_ENTRY_CHECK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   the event classification WinForm, only [System.Windows.Forms.Control] can specify.and the event classification WPF, only [System.Windows.DependencyObject] can specify. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ASYNC_EVENT_ENTRY_CONTROL_CHECK_ERROR {
            get {
                return ResourceManager.GetString("ASYNC_EVENT_ENTRY_CONTROL_CHECK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type of argument needs to be in any of System.Windows.DependencyObject and System.Windows.Forms.Control. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ASYNC_FUNC_CHECK_ERROR {
            get {
                return ResourceManager.GetString("ASYNC_FUNC_CHECK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MessageBox display API to be used has an error (for WPF &lt;=&gt; for Windows). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ASYNC_MSGBOX_ERROR {
            get {
                return ResourceManager.GetString("ASYNC_MSGBOX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control overlaps in a screen (a master page, a contents page, user control). (Control name : {0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONTROL_REPETITION_ERROR1 {
            get {
                return ResourceManager.GetString("CONTROL_REPETITION_ERROR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control overlaps in a screen (form, user control). (Control name : {0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONTROL_REPETITION_ERROR2 {
            get {
                return ResourceManager.GetString("CONTROL_REPETITION_ERROR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The prefix and type of control are not in agreement (prefix: {0}, type : {1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONTROL_TYPE_ERROR {
            get {
                return ResourceManager.GetString("CONTROL_TYPE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The unjust state was detected by post-processing after a dialog display. Supplementary information : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_AFTER_PROCESSING_STATUS_ERROR {
            get {
                return ResourceManager.GetString("DIALOG_AFTER_PROCESSING_STATUS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The unjust state was detected by the processing which closes a dialog. Supplementary information : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_CLOSING_STATUS_ERROR {
            get {
                return ResourceManager.GetString("DIALOG_CLOSING_STATUS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A CloseModalScreen_NoPostback() method cannot be performed from this screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_CLOSING_STATUS_ERROR1 {
            get {
                return ResourceManager.GetString("DIALOG_CLOSING_STATUS_ERROR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A CloseModalScreen_WithAllParent() method cannot be performed from this screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_CLOSING_STATUS_ERROR2 {
            get {
                return ResourceManager.GetString("DIALOG_CLOSING_STATUS_ERROR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify definition numerically. Config key: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_IN_WRITING_OF_FX_NUMVAL {
            get {
                return ResourceManager.GetString("ERROR_IN_WRITING_OF_FX_NUMVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path information on definition file is not defined. Config key: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_IN_WRITING_OF_FX_PATH1 {
            get {
                return ResourceManager.GetString("ERROR_IN_WRITING_OF_FX_PATH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path information on definition file is wrong. Config key: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_IN_WRITING_OF_FX_PATH2 {
            get {
                return ResourceManager.GetString("ERROR_IN_WRITING_OF_FX_PATH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify switch by &quot;on&quot; or &quot;off&quot;. Config key: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_IN_WRITING_OF_FX_SWITCH1 {
            get {
                return ResourceManager.GetString("ERROR_IN_WRITING_OF_FX_SWITCH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify switch by &quot;true&quot; or &quot;false&quot;. Config key: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_IN_WRITING_OF_FX_SWITCH2 {
            get {
                return ResourceManager.GetString("ERROR_IN_WRITING_OF_FX_SWITCH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The unjust state was detected by framework processing. Supplementary information : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FX_PROCESSING_STATUS_ERROR {
            get {
                return ResourceManager.GetString("FX_PROCESSING_STATUS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Button history information cannot be referred to by the causes which carried out session timeout, having referred to old cache, such as dequeued from queue. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FX_PROCESSING_STATUS_ERROR_NO_BH_QUEUE {
            get {
                return ResourceManager.GetString("FX_PROCESSING_STATUS_ERROR_NO_BH_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The error occurred in manipulation check processing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ILLEGAL_OPERATION_CHECK_ERROR {
            get {
                return ResourceManager.GetString("ILLEGAL_OPERATION_CHECK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The format of the name resolution definition file of in process call is inaccurate. :{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IPR_NAMESERVICE_XML_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("IPR_NAMESERVICE_XML_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no  FxLiteral.XML_TM_INPROCESS_ATTR_ASSEMBLYNAME attribute. FxLiteral.XML_TM_TAG_TRANSMISSION tag ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IPR_NAMESERVICE_XML_FORMAT_ERROR_asmName1 {
            get {
                return ResourceManager.GetString("IPR_NAMESERVICE_XML_FORMAT_ERROR_asmName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A FxLiteral.XML_TM_INPROCESS_ATTR_ASSEMBLYNAME attribute value is empty. FxLiteral.XML_TM_TAG_TRANSMISSION tag ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IPR_NAMESERVICE_XML_FORMAT_ERROR_asmName2 {
            get {
                return ResourceManager.GetString("IPR_NAMESERVICE_XML_FORMAT_ERROR_asmName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A  FxLiteral.XML_TM_INPROCESS_ATTR_CLASSNAME tag ({0}) with a FxLiteral.XML_TM_TAG_TRANSMISSION attribute. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IPR_NAMESERVICE_XML_FORMAT_ERROR_clsName1 {
            get {
                return ResourceManager.GetString("IPR_NAMESERVICE_XML_FORMAT_ERROR_clsName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A FxLiteral.XML_TM_INPROCESS_ATTR_CLASSNAME attribute value is empty. FxLiteral.XML_TM_TAG_TRANSMISSION tag ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IPR_NAMESERVICE_XML_FORMAT_ERROR_clsName2 {
            get {
                return ResourceManager.GetString("IPR_NAMESERVICE_XML_FORMAT_ERROR_clsName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The error occurred in B layer call check processing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LB_ILLEGAL_CALL_CHECK_ERROR {
            get {
                return ResourceManager.GetString("LB_ILLEGAL_CALL_CHECK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   master page has not inherited BaseMasterController (master page name : {0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MASTER_PAGE_TYPE_ERROR {
            get {
                return ResourceManager.GetString("MASTER_PAGE_TYPE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The format of message definition file is inaccurate. :{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_XML_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("MESSAGE_XML_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no {0} attribute. Message tag ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_XML_FORMAT_ERROR_ATTR {
            get {
                return ResourceManager.GetString("MESSAGE_XML_FORMAT_ERROR_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no id attribute value ({0}) corresponding to a FxLiteral.XML_TM_TAG_TRANSMISSION tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NAMESERVICE_XML_FORMAT_ERROR_tm {
            get {
                return ResourceManager.GetString("NAMESERVICE_XML_FORMAT_ERROR_tm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The HIDDEN tag required of framework is not mounted. HIDDEN tag: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_FX_HIDDEN {
            get {
                return ResourceManager.GetString("NO_FX_HIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Master page is not used (contents page name : {0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_MASTER_PAGE {
            get {
                return ResourceManager.GetString("NO_MASTER_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is the check error of a parameter. : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PARAMETER_CHECK_ERROR {
            get {
                return ResourceManager.GetString("PARAMETER_CHECK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   parameter is empty ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PARAMETER_CHECK_ERROR_empty {
            get {
                return ResourceManager.GetString("PARAMETER_CHECK_ERROR_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   parameter length is inaccurate ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PARAMETER_CHECK_ERROR_length {
            get {
                return ResourceManager.GetString("PARAMETER_CHECK_ERROR_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   parameter is null ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PARAMETER_CHECK_ERROR_null {
            get {
                return ResourceManager.GetString("PARAMETER_CHECK_ERROR_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The format of the name resolution definition file of a call protocol is inaccurate. :{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRT_NAMESERVICE_XML_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("PRT_NAMESERVICE_XML_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no FxLiteral.XML_TM_PROTOCOL_TAG_PROP  tag. IDREF ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRT_NAMESERVICE_XML_FORMAT_ERROR_prop1 {
            get {
                return ResourceManager.GetString("PRT_NAMESERVICE_XML_FORMAT_ERROR_prop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no  FxLiteral.XML_CMN_ATTR_VALUE  attribute. FxLiteral.XML_TM_PROTOCOL_TAG_PROP  tag ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRT_NAMESERVICE_XML_FORMAT_ERROR_prop2 {
            get {
                return ResourceManager.GetString("PRT_NAMESERVICE_XML_FORMAT_ERROR_prop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no FxLiteral.XML_TM_PROTOCOL_ATTR_PROTOCOL attribute. FxLiteral.XML_TM_TAG_TRANSMISSION tag ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRT_NAMESERVICE_XML_FORMAT_ERROR_prt1 {
            get {
                return ResourceManager.GetString("PRT_NAMESERVICE_XML_FORMAT_ERROR_prt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A setup of a FxLiteral.XML_TM_PROTOCOL_ATTR_PROTOCOL attribute is inaccurate ({0}). FxLiteral.XML_TM_TAG_TRANSMISSION tag ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRT_NAMESERVICE_XML_FORMAT_ERROR_prt2 {
            get {
                return ResourceManager.GetString("PRT_NAMESERVICE_XML_FORMAT_ERROR_prt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The  FxLiteral.XML_TM_PROTOCOL_ATTR_TIMEOUT attribute value should specify a numerical value. FxLiteral.XML_TM_TAG_TRANSMISSION  tag ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRT_NAMESERVICE_XML_FORMAT_ERROR_to {
            get {
                return ResourceManager.GetString("PRT_NAMESERVICE_XML_FORMAT_ERROR_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are not FxLiteral.XML_TM_PROTOCOL_ATTR_URL and a FxLiteral.XML_TM_PROTOCOL_ATTR_URL_REF attribute. FxLiteral.XML_TM_TAG_TRANSMISSION tag ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRT_NAMESERVICE_XML_FORMAT_ERROR_url1 {
            get {
                return ResourceManager.GetString("PRT_NAMESERVICE_XML_FORMAT_ERROR_url1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no  FxLiteral.XML_TM_PROTOCOL_TAG_URL  tag. IDREF ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRT_NAMESERVICE_XML_FORMAT_ERROR_url2 {
            get {
                return ResourceManager.GetString("PRT_NAMESERVICE_XML_FORMAT_ERROR_url2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no  FxLiteral.XML_CMN_ATTR_VALUE attribute. FxLiteral.XML_TM_PROTOCOL_TAG_URL  tag ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRT_NAMESERVICE_XML_FORMAT_ERROR_url3 {
            get {
                return ResourceManager.GetString("PRT_NAMESERVICE_XML_FORMAT_ERROR_url3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   url is empty. {0} tags ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRT_NAMESERVICE_XML_FORMAT_ERROR_url4 {
            get {
                return ResourceManager.GetString("PRT_NAMESERVICE_XML_FORMAT_ERROR_url4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The error occurred in screen changes check processing. :{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCREEN_CONTROL_CHECK_ERROR {
            get {
                return ResourceManager.GetString("SCREEN_CONTROL_CHECK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen changes by a Get method are not permitted ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCREEN_CONTROL_CHECK_ERROR_get {
            get {
                return ResourceManager.GetString("SCREEN_CONTROL_CHECK_ERROR_get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The screen changes which do not use parts (Transfer and crossing site posting) are not permitted ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCREEN_CONTROL_CHECK_ERROR_naked {
            get {
                return ResourceManager.GetString("SCREEN_CONTROL_CHECK_ERROR_naked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   the screen changes concerned are not permitted (path of a front screen : {0}, path of the present screen : {1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCREEN_CONTROL_CHECK_ERROR_nolbl {
            get {
                return ResourceManager.GetString("SCREEN_CONTROL_CHECK_ERROR_nolbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The format of a screen changes definition file is inaccurate. :{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCREEN_CONTROL_XML_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("SCREEN_CONTROL_XML_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no  FxLiteral.XML_SC_ATTR_DIRECTLINK attribute.  FxLiteral.XML_SC_TAG_SCREEN tags ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCREEN_CONTROL_XML_FORMAT_ERROR_dl1 {
            get {
                return ResourceManager.GetString("SCREEN_CONTROL_XML_FORMAT_ERROR_dl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A  FxLiteral.XML_SC_ATTR_DIRECTLINK attribute is inaccurate({0}). FxLiteral.XML_SC_TAG_SCREEN  tags ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCREEN_CONTROL_XML_FORMAT_ERROR_dl2 {
            get {
                return ResourceManager.GetString("SCREEN_CONTROL_XML_FORMAT_ERROR_dl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no  FxLiteral.XML_SC_ATTR_LABEL  attribute. {0} tags ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCREEN_CONTROL_XML_FORMAT_ERROR_label {
            get {
                return ResourceManager.GetString("SCREEN_CONTROL_XML_FORMAT_ERROR_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A   FxLiteral.XML_SC_ATTR_MODE  attribute is inaccurate ({0}). {1} tag ({2}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCREEN_CONTROL_XML_FORMAT_ERROR_mode {
            get {
                return ResourceManager.GetString("SCREEN_CONTROL_XML_FORMAT_ERROR_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no  FxLiteral.XML_CMN_ATTR_VALUE  attribute. {0} tags ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCREEN_CONTROL_XML_FORMAT_ERROR_value {
            get {
                return ResourceManager.GetString("SCREEN_CONTROL_XML_FORMAT_ERROR_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is session timeout. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SESSION_TIMEOUT {
            get {
                return ResourceManager.GetString("SESSION_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The format of share information definition file is inaccurate. :{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHAREDPROPERTY_XML_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("SHAREDPROPERTY_XML_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no {0} attribute. SharedProp tag ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHAREDPROPERTY_XML_FORMAT_ERROR_ATTR {
            get {
                return ResourceManager.GetString("SHAREDPROPERTY_XML_FORMAT_ERROR_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The format of a transaction control definition file is inaccurate. :{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TRANSACTION_CONTROL_XML_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("TRANSACTION_CONTROL_XML_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no  FxLiteral.XML_TX_ATTR_ISOLEVEL attribute. FxLiteral.XML_TX_TAG_TRANSACTION_PATTERN tag ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TRANSACTION_CONTROL_XML_FORMAT_ERROR_iso1 {
            get {
                return ResourceManager.GetString("TRANSACTION_CONTROL_XML_FORMAT_ERROR_iso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A FxLiteral.XML_TX_ATTR_ISOLEVEL attribute is inaccurate ({0}). FxLiteral.XML_TX_TAG_TRANSACTION_PATTERN tag ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TRANSACTION_CONTROL_XML_FORMAT_ERROR_iso2 {
            get {
                return ResourceManager.GetString("TRANSACTION_CONTROL_XML_FORMAT_ERROR_iso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no id attribute value ({0}) corresponding to a FxLiteral.XML_TX_TAG_TRANSACTION_GROUP tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TRANSACTION_CONTROL_XML_FORMAT_ERROR_tg {
            get {
                return ResourceManager.GetString("TRANSACTION_CONTROL_XML_FORMAT_ERROR_tg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no FxLiteral.XML_CMN_ATTR_VALUE attribute. FxLiteral.XML_TX_TAG_TRANSACTION_GROUP tag ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TRANSACTION_CONTROL_XML_FORMAT_ERROR_tgval {
            get {
                return ResourceManager.GetString("TRANSACTION_CONTROL_XML_FORMAT_ERROR_tgval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no id attribute value ({0}) corresponding to a FxLiteral.XML_TX_TAG_TRANSACTION_PATTERN tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TRANSACTION_CONTROL_XML_FORMAT_ERROR_tp {
            get {
                return ResourceManager.GetString("TRANSACTION_CONTROL_XML_FORMAT_ERROR_tp", resourceCulture);
            }
        }
    }
}
