'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Aspx_Common_testNest_testScreen1bmp2

    '''<summary>
    '''lblCPF_A1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCPF_A1 As Global.Touryo.Infrastructure.CustomControl.WebCustomLabel

    '''<summary>
    '''btnCPF_A1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCPF_A1 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''ContentPlaceHolder_A2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder_A2 As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''lblCPF_B1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCPF_B1 As Global.Touryo.Infrastructure.CustomControl.WebCustomLabel

    '''<summary>
    '''btnCPF_B1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCPF_B1 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''ContentPlaceHolder_B2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder_B2 As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''lblCPF_C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCPF_C1 As Global.Touryo.Infrastructure.CustomControl.WebCustomLabel

    '''<summary>
    '''btnCPF_C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCPF_C1 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

    '''<summary>
    '''ContentPlaceHolder_C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder_C2 As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
