//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18033
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace WSClientWinStore_sample.SbServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shipper", Namespace="http://tempuri.org/")]
    public partial class Shipper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ShipperIDField;
        
        private string CompanyNameField;
        
        private string PhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ShipperID {
            get {
                return this.ShipperIDField;
            }
            set {
                if ((this.ShipperIDField.Equals(value) != true)) {
                    this.ShipperIDField = value;
                    this.RaisePropertyChanged("ShipperID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SbServiceReference.ServiceForSbSoap")]
    public interface ServiceForSbSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectCount", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectCountResponse> SelectCountAsync(WSClientWinStore_sample.SbServiceReference.SelectCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAll_DT", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectAll_DTResponse> SelectAll_DTAsync(WSClientWinStore_sample.SbServiceReference.SelectAll_DTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAll_DS", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectAll_DSResponse> SelectAll_DSAsync(WSClientWinStore_sample.SbServiceReference.SelectAll_DSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAll_DR", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectAll_DRResponse> SelectAll_DRAsync(WSClientWinStore_sample.SbServiceReference.SelectAll_DRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAll_DSQL", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectAll_DSQLResponse> SelectAll_DSQLAsync(WSClientWinStore_sample.SbServiceReference.SelectAll_DSQLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectResponse> SelectAsync(WSClientWinStore_sample.SbServiceReference.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.InsertResponse> InsertAsync(WSClientWinStore_sample.SbServiceReference.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.UpdateResponse> UpdateAsync(WSClientWinStore_sample.SbServiceReference.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.DeleteResponse> DeleteAsync(WSClientWinStore_sample.SbServiceReference.DeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectCount", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.SelectCountRequestBody Body;
        
        public SelectCountRequest() {
        }
        
        public SelectCountRequest(WSClientWinStore_sample.SbServiceReference.SelectCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string actionType;
        
        public SelectCountRequestBody() {
        }
        
        public SelectCountRequestBody(string context, string actionType) {
            this.context = context;
            this.actionType = actionType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.SelectCountResponseBody Body;
        
        public SelectCountResponse() {
        }
        
        public SelectCountResponse(WSClientWinStore_sample.SbServiceReference.SelectCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectCountResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int returnValue;
        
        public SelectCountResponseBody() {
        }
        
        public SelectCountResponseBody(string SelectCountResult, string context, int returnValue) {
            this.SelectCountResult = SelectCountResult;
            this.context = context;
            this.returnValue = returnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAll_DTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAll_DT", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.SelectAll_DTRequestBody Body;
        
        public SelectAll_DTRequest() {
        }
        
        public SelectAll_DTRequest(WSClientWinStore_sample.SbServiceReference.SelectAll_DTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAll_DTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string actionType;
        
        public SelectAll_DTRequestBody() {
        }
        
        public SelectAll_DTRequestBody(string context, string actionType) {
            this.context = context;
            this.actionType = actionType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAll_DTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAll_DTResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.SelectAll_DTResponseBody Body;
        
        public SelectAll_DTResponse() {
        }
        
        public SelectAll_DTResponse(WSClientWinStore_sample.SbServiceReference.SelectAll_DTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAll_DTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectAll_DTResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.ObjectModel.ObservableCollection<WSClientWinStore_sample.SbServiceReference.Shipper> returnValue;
        
        public SelectAll_DTResponseBody() {
        }
        
        public SelectAll_DTResponseBody(string SelectAll_DTResult, string context, System.Collections.ObjectModel.ObservableCollection<WSClientWinStore_sample.SbServiceReference.Shipper> returnValue) {
            this.SelectAll_DTResult = SelectAll_DTResult;
            this.context = context;
            this.returnValue = returnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAll_DSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAll_DS", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.SelectAll_DSRequestBody Body;
        
        public SelectAll_DSRequest() {
        }
        
        public SelectAll_DSRequest(WSClientWinStore_sample.SbServiceReference.SelectAll_DSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAll_DSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string actionType;
        
        public SelectAll_DSRequestBody() {
        }
        
        public SelectAll_DSRequestBody(string context, string actionType) {
            this.context = context;
            this.actionType = actionType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAll_DSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAll_DSResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.SelectAll_DSResponseBody Body;
        
        public SelectAll_DSResponse() {
        }
        
        public SelectAll_DSResponse(WSClientWinStore_sample.SbServiceReference.SelectAll_DSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAll_DSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectAll_DSResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.ObjectModel.ObservableCollection<WSClientWinStore_sample.SbServiceReference.Shipper> returnValue;
        
        public SelectAll_DSResponseBody() {
        }
        
        public SelectAll_DSResponseBody(string SelectAll_DSResult, string context, System.Collections.ObjectModel.ObservableCollection<WSClientWinStore_sample.SbServiceReference.Shipper> returnValue) {
            this.SelectAll_DSResult = SelectAll_DSResult;
            this.context = context;
            this.returnValue = returnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAll_DRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAll_DR", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.SelectAll_DRRequestBody Body;
        
        public SelectAll_DRRequest() {
        }
        
        public SelectAll_DRRequest(WSClientWinStore_sample.SbServiceReference.SelectAll_DRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAll_DRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string actionType;
        
        public SelectAll_DRRequestBody() {
        }
        
        public SelectAll_DRRequestBody(string context, string actionType) {
            this.context = context;
            this.actionType = actionType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAll_DRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAll_DRResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.SelectAll_DRResponseBody Body;
        
        public SelectAll_DRResponse() {
        }
        
        public SelectAll_DRResponse(WSClientWinStore_sample.SbServiceReference.SelectAll_DRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAll_DRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectAll_DRResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.ObjectModel.ObservableCollection<WSClientWinStore_sample.SbServiceReference.Shipper> returnValue;
        
        public SelectAll_DRResponseBody() {
        }
        
        public SelectAll_DRResponseBody(string SelectAll_DRResult, string context, System.Collections.ObjectModel.ObservableCollection<WSClientWinStore_sample.SbServiceReference.Shipper> returnValue) {
            this.SelectAll_DRResult = SelectAll_DRResult;
            this.context = context;
            this.returnValue = returnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAll_DSQLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAll_DSQL", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.SelectAll_DSQLRequestBody Body;
        
        public SelectAll_DSQLRequest() {
        }
        
        public SelectAll_DSQLRequest(WSClientWinStore_sample.SbServiceReference.SelectAll_DSQLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAll_DSQLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string actionType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orderColumn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string orderSequence;
        
        public SelectAll_DSQLRequestBody() {
        }
        
        public SelectAll_DSQLRequestBody(string context, string actionType, string orderColumn, string orderSequence) {
            this.context = context;
            this.actionType = actionType;
            this.orderColumn = orderColumn;
            this.orderSequence = orderSequence;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAll_DSQLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAll_DSQLResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.SelectAll_DSQLResponseBody Body;
        
        public SelectAll_DSQLResponse() {
        }
        
        public SelectAll_DSQLResponse(WSClientWinStore_sample.SbServiceReference.SelectAll_DSQLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAll_DSQLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectAll_DSQLResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.ObjectModel.ObservableCollection<WSClientWinStore_sample.SbServiceReference.Shipper> returnValue;
        
        public SelectAll_DSQLResponseBody() {
        }
        
        public SelectAll_DSQLResponseBody(string SelectAll_DSQLResult, string context, System.Collections.ObjectModel.ObservableCollection<WSClientWinStore_sample.SbServiceReference.Shipper> returnValue) {
            this.SelectAll_DSQLResult = SelectAll_DSQLResult;
            this.context = context;
            this.returnValue = returnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.SelectRequestBody Body;
        
        public SelectRequest() {
        }
        
        public SelectRequest(WSClientWinStore_sample.SbServiceReference.SelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string actionType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int shipperID;
        
        public SelectRequestBody() {
        }
        
        public SelectRequestBody(string context, string actionType, int shipperID) {
            this.context = context;
            this.actionType = actionType;
            this.shipperID = shipperID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.SelectResponseBody Body;
        
        public SelectResponse() {
        }
        
        public SelectResponse(WSClientWinStore_sample.SbServiceReference.SelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WSClientWinStore_sample.SbServiceReference.Shipper returnValue;
        
        public SelectResponseBody() {
        }
        
        public SelectResponseBody(string SelectResult, string context, WSClientWinStore_sample.SbServiceReference.Shipper returnValue) {
            this.SelectResult = SelectResult;
            this.context = context;
            this.returnValue = returnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(WSClientWinStore_sample.SbServiceReference.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string actionType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string companyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string phone;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(string context, string actionType, string companyName, string phone) {
            this.context = context;
            this.actionType = actionType;
            this.companyName = companyName;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(WSClientWinStore_sample.SbServiceReference.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int returnValue;
        
        public InsertResponseBody() {
        }
        
        public InsertResponseBody(string InsertResult, string context, int returnValue) {
            this.InsertResult = InsertResult;
            this.context = context;
            this.returnValue = returnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(WSClientWinStore_sample.SbServiceReference.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string actionType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WSClientWinStore_sample.SbServiceReference.Shipper shipper;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(string context, string actionType, WSClientWinStore_sample.SbServiceReference.Shipper shipper) {
            this.context = context;
            this.actionType = actionType;
            this.shipper = shipper;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(WSClientWinStore_sample.SbServiceReference.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int returnValue;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(string UpdateResult, string context, int returnValue) {
            this.UpdateResult = UpdateResult;
            this.context = context;
            this.returnValue = returnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(WSClientWinStore_sample.SbServiceReference.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string actionType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int shipperID;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string context, string actionType, int shipperID) {
            this.context = context;
            this.actionType = actionType;
            this.shipperID = shipperID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClientWinStore_sample.SbServiceReference.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(WSClientWinStore_sample.SbServiceReference.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int returnValue;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(string DeleteResult, string context, int returnValue) {
            this.DeleteResult = DeleteResult;
            this.context = context;
            this.returnValue = returnValue;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceForSbSoapChannel : WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceForSbSoapClient : System.ServiceModel.ClientBase<WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap>, WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceForSbSoapClient() : 
                base(ServiceForSbSoapClient.GetDefaultBinding(), ServiceForSbSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.ServiceForSbSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceForSbSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceForSbSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceForSbSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceForSbSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceForSbSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceForSbSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceForSbSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceForSbSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectCountResponse> WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap.SelectCountAsync(WSClientWinStore_sample.SbServiceReference.SelectCountRequest request) {
            return base.Channel.SelectCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectCountResponse> SelectCountAsync(string context, string actionType) {
            WSClientWinStore_sample.SbServiceReference.SelectCountRequest inValue = new WSClientWinStore_sample.SbServiceReference.SelectCountRequest();
            inValue.Body = new WSClientWinStore_sample.SbServiceReference.SelectCountRequestBody();
            inValue.Body.context = context;
            inValue.Body.actionType = actionType;
            return ((WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap)(this)).SelectCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectAll_DTResponse> WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap.SelectAll_DTAsync(WSClientWinStore_sample.SbServiceReference.SelectAll_DTRequest request) {
            return base.Channel.SelectAll_DTAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectAll_DTResponse> SelectAll_DTAsync(string context, string actionType) {
            WSClientWinStore_sample.SbServiceReference.SelectAll_DTRequest inValue = new WSClientWinStore_sample.SbServiceReference.SelectAll_DTRequest();
            inValue.Body = new WSClientWinStore_sample.SbServiceReference.SelectAll_DTRequestBody();
            inValue.Body.context = context;
            inValue.Body.actionType = actionType;
            return ((WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap)(this)).SelectAll_DTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectAll_DSResponse> WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap.SelectAll_DSAsync(WSClientWinStore_sample.SbServiceReference.SelectAll_DSRequest request) {
            return base.Channel.SelectAll_DSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectAll_DSResponse> SelectAll_DSAsync(string context, string actionType) {
            WSClientWinStore_sample.SbServiceReference.SelectAll_DSRequest inValue = new WSClientWinStore_sample.SbServiceReference.SelectAll_DSRequest();
            inValue.Body = new WSClientWinStore_sample.SbServiceReference.SelectAll_DSRequestBody();
            inValue.Body.context = context;
            inValue.Body.actionType = actionType;
            return ((WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap)(this)).SelectAll_DSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectAll_DRResponse> WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap.SelectAll_DRAsync(WSClientWinStore_sample.SbServiceReference.SelectAll_DRRequest request) {
            return base.Channel.SelectAll_DRAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectAll_DRResponse> SelectAll_DRAsync(string context, string actionType) {
            WSClientWinStore_sample.SbServiceReference.SelectAll_DRRequest inValue = new WSClientWinStore_sample.SbServiceReference.SelectAll_DRRequest();
            inValue.Body = new WSClientWinStore_sample.SbServiceReference.SelectAll_DRRequestBody();
            inValue.Body.context = context;
            inValue.Body.actionType = actionType;
            return ((WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap)(this)).SelectAll_DRAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectAll_DSQLResponse> WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap.SelectAll_DSQLAsync(WSClientWinStore_sample.SbServiceReference.SelectAll_DSQLRequest request) {
            return base.Channel.SelectAll_DSQLAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectAll_DSQLResponse> SelectAll_DSQLAsync(string context, string actionType, string orderColumn, string orderSequence) {
            WSClientWinStore_sample.SbServiceReference.SelectAll_DSQLRequest inValue = new WSClientWinStore_sample.SbServiceReference.SelectAll_DSQLRequest();
            inValue.Body = new WSClientWinStore_sample.SbServiceReference.SelectAll_DSQLRequestBody();
            inValue.Body.context = context;
            inValue.Body.actionType = actionType;
            inValue.Body.orderColumn = orderColumn;
            inValue.Body.orderSequence = orderSequence;
            return ((WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap)(this)).SelectAll_DSQLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectResponse> WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap.SelectAsync(WSClientWinStore_sample.SbServiceReference.SelectRequest request) {
            return base.Channel.SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.SelectResponse> SelectAsync(string context, string actionType, int shipperID) {
            WSClientWinStore_sample.SbServiceReference.SelectRequest inValue = new WSClientWinStore_sample.SbServiceReference.SelectRequest();
            inValue.Body = new WSClientWinStore_sample.SbServiceReference.SelectRequestBody();
            inValue.Body.context = context;
            inValue.Body.actionType = actionType;
            inValue.Body.shipperID = shipperID;
            return ((WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap)(this)).SelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.InsertResponse> WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap.InsertAsync(WSClientWinStore_sample.SbServiceReference.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.InsertResponse> InsertAsync(string context, string actionType, string companyName, string phone) {
            WSClientWinStore_sample.SbServiceReference.InsertRequest inValue = new WSClientWinStore_sample.SbServiceReference.InsertRequest();
            inValue.Body = new WSClientWinStore_sample.SbServiceReference.InsertRequestBody();
            inValue.Body.context = context;
            inValue.Body.actionType = actionType;
            inValue.Body.companyName = companyName;
            inValue.Body.phone = phone;
            return ((WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.UpdateResponse> WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap.UpdateAsync(WSClientWinStore_sample.SbServiceReference.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.UpdateResponse> UpdateAsync(string context, string actionType, WSClientWinStore_sample.SbServiceReference.Shipper shipper) {
            WSClientWinStore_sample.SbServiceReference.UpdateRequest inValue = new WSClientWinStore_sample.SbServiceReference.UpdateRequest();
            inValue.Body = new WSClientWinStore_sample.SbServiceReference.UpdateRequestBody();
            inValue.Body.context = context;
            inValue.Body.actionType = actionType;
            inValue.Body.shipper = shipper;
            return ((WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.DeleteResponse> WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap.DeleteAsync(WSClientWinStore_sample.SbServiceReference.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClientWinStore_sample.SbServiceReference.DeleteResponse> DeleteAsync(string context, string actionType, int shipperID) {
            WSClientWinStore_sample.SbServiceReference.DeleteRequest inValue = new WSClientWinStore_sample.SbServiceReference.DeleteRequest();
            inValue.Body = new WSClientWinStore_sample.SbServiceReference.DeleteRequestBody();
            inValue.Body.context = context;
            inValue.Body.actionType = actionType;
            inValue.Body.shipperID = shipperID;
            return ((WSClientWinStore_sample.SbServiceReference.ServiceForSbSoap)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ServiceForSbSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ServiceForSbSoap)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:9996/WSClientSL_sample/WebService/ServiceForSb.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ServiceForSbSoapClient.GetBindingForEndpoint(EndpointConfiguration.ServiceForSbSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ServiceForSbSoapClient.GetEndpointAddress(EndpointConfiguration.ServiceForSbSoap);
        }
        
        public enum EndpointConfiguration {
            
            ServiceForSbSoap,
        }
    }
}
