SELECT * FROM ADMINISTRATOR.EMPLOYEE
WHERE
EMPNO IN (SELECT EMPNO FROM ADMINISTRATOR.EMPLOYEE)
AND FIRSTNME = @FN AND LASTNAME = @LN
ORDER BY %COLUMN% %SEQUENCE%

/*PARAM*FN,String,CHRISTINE*PARAM*/
/*PARAM*LN,String,HAAS*PARAM*/
/*PARAM*COLUMN,EMPNO*PARAM*/
/*PARAM*SEQUENCE,DESC*PARAM*/

-- パラメタ設定済み