//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touryo.Infrastructure.Public.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PublicExceptionMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublicExceptionMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Touryo.Infrastructure.Public.Resources.PublicExceptionMessageResource", typeof(PublicExceptionMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument injustice..
        /// </summary>
        internal static string ARGUMENT_INJUSTICE {
            get {
                return ResourceManager.GetString("ARGUMENT_INJUSTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify one or more numerical values (second) as a CommandTimeout value.Config key:.
        /// </summary>
        internal static string COMMANDTIMEOUT_ERROR {
            get {
                return ResourceManager.GetString("COMMANDTIMEOUT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invalid parameter [NotConnect] was specified as DbEnum.IsolationLevelEnum iso. [NotConnect] parameter cannot be used..
        /// </summary>
        internal static string DB_ISO_LEVEL_PARAM_ERROR_NC {
            get {
                return ResourceManager.GetString("DB_ISO_LEVEL_PARAM_ERROR_NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invalid isolation level [RepeatableRead] was specified as DbEnum.IsolationLevelEnum iso in {0} databases..
        /// </summary>
        internal static string DB_ISO_LEVEL_PARAM_ERROR_RR {
            get {
                return ResourceManager.GetString("DB_ISO_LEVEL_PARAM_ERROR_RR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invalid isolation level [Snapshot] was specified as DbEnum.IsolationLevelEnum iso in {0} databases..
        /// </summary>
        internal static string DB_ISO_LEVEL_PARAM_ERROR_SS {
            get {
                return ResourceManager.GetString("DB_ISO_LEVEL_PARAM_ERROR_SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invalid isolation level [ReadUncommitted] was specified as DbEnum.IsolationLevelEnum iso in {0} databases..
        /// </summary>
        internal static string DB_ISO_LEVEL_PARAM_ERROR_UC {
            get {
                return ResourceManager.GetString("DB_ISO_LEVEL_PARAM_ERROR_UC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invalid parameter [User] was specified as DbEnum.IsolationLevelEnum iso. A user needs to change [User] parameter to other isolation levels..
        /// </summary>
        internal static string DB_ISO_LEVEL_PARAM_ERROR_USR {
            get {
                return ResourceManager.GetString("DB_ISO_LEVEL_PARAM_ERROR_USR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ELSE tag is not set up although false was set to the parameter in a tag of IF tag..
        /// </summary>
        internal static string DPQ_ELSE_TAG_DOESNT_EXIST_WHEN_INNER_PARAM_OF_IF_TAG_IS_FALSE {
            get {
                return ResourceManager.GetString("DPQ_ELSE_TAG_DOESNT_EXIST_WHEN_INNER_PARAM_OF_IF_TAG_IS_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ELSE tag is not set up although null was set to the parameter in a tag of IF tag..
        /// </summary>
        internal static string DPQ_ELSE_TAG_DOESNT_EXIST_WHEN_INNER_PARAM_OF_IF_TAG_IS_NULL {
            get {
                return ResourceManager.GetString("DPQ_ELSE_TAG_DOESNT_EXIST_WHEN_INNER_PARAM_OF_IF_TAG_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ELSE tag is not set up although null was set to the parameter in a text of IF tag..
        /// </summary>
        internal static string DPQ_ELSE_TAG_DOESNT_EXIST_WHEN_TEXT_PARAM_OF_IF_TAG_IS_NULL {
            get {
                return ResourceManager.GetString("DPQ_ELSE_TAG_DOESNT_EXIST_WHEN_TEXT_PARAM_OF_IF_TAG_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value which can be set as the parameter in a tag of {0} tag is only a null value or Boolean value..
        /// </summary>
        internal static string DPQ_SET_ONLY_NULL_OR_BOOL_TO_INNER_PARAM_VALUE {
            get {
                return ResourceManager.GetString("DPQ_SET_ONLY_NULL_OR_BOOL_TO_INNER_PARAM_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of {0} tag is inaccurate..
        /// </summary>
        internal static string DPQ_TAG_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("DPQ_TAG_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter in a tag is not set to {0} tag..
        /// </summary>
        internal static string DPQ_TAG_INNER_PARAM_NOT_EXIST {
            get {
                return ResourceManager.GetString("DPQ_TAG_INNER_PARAM_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name attribute is not set to {0} tag (null)..
        /// </summary>
        internal static string DPQ_TAG_NAME_ATTR_NOT_EXIST {
            get {
                return ResourceManager.GetString("DPQ_TAG_NAME_ATTR_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name attribute is not set to {0} tag (null character sequence)..
        /// </summary>
        internal static string DPQ_TAG_NAME_ATTR_VALUE_IS_EMPTY {
            get {
                return ResourceManager.GetString("DPQ_TAG_NAME_ATTR_VALUE_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value attribute is not set to {0} tag (null)..
        /// </summary>
        internal static string DPQ_TAG_VALUE_ATTR_NOT_EXIST {
            get {
                return ResourceManager.GetString("DPQ_TAG_VALUE_ATTR_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assembly name: [{0}] does not exist..
        /// </summary>
        internal static string LATEBIND_ERROR0 {
            get {
                return ResourceManager.GetString("LATEBIND_ERROR0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class name: [{1}] does not exist in assembly name: [{0}]..
        /// </summary>
        internal static string LATEBIND_ERROR1 {
            get {
                return ResourceManager.GetString("LATEBIND_ERROR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method name: [{2}] does not exist in assembly name: [{0}] and class name: [{1}]..
        /// </summary>
        internal static string LATEBIND_ERROR2 {
            get {
                return ResourceManager.GetString("LATEBIND_ERROR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method name: [{2}] whose number of arguments corresponds does not exist in assembly name: [{0}] and class name: [{1}]..
        /// </summary>
        internal static string LATEBIND_ERROR3 {
            get {
                return ResourceManager.GetString("LATEBIND_ERROR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config does not have specification. Config key:{0}.
        /// </summary>
        internal static string NO_CONFIG {
            get {
                return ResourceManager.GetString("NO_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This processing is not implemented.
        /// </summary>
        internal static string NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process is not supported.
        /// </summary>
        internal static string NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must declare the scalar variable &quot;{0}&quot;..
        /// </summary>
        internal static string ORDER_BIND_ERROR_PARAMETER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ORDER_BIND_ERROR_PARAMETER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parameter is null..
        /// </summary>
        internal static string PARAM_IS_NULL {
            get {
                return ResourceManager.GetString("PARAM_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion of parameter information ({0}) went wrong. :{1}.
        /// </summary>
        internal static string PARAM_TAG_ERROR {
            get {
                return ResourceManager.GetString("PARAM_TAG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type specification is inaccurate ({0})..
        /// </summary>
        internal static string PARAM_TAG_TYPE_ERROR {
            get {
                return ResourceManager.GetString("PARAM_TAG_TYPE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value specification is inaccurate ({0})..
        /// </summary>
        internal static string PARAM_TAG_VALUE_ERROR {
            get {
                return ResourceManager.GetString("PARAM_TAG_VALUE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property character string format is inaccurate. :{0}.
        /// </summary>
        internal static string PROP_STRING_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("PROP_STRING_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curly brace is not closed correctly..
        /// </summary>
        internal static string PROP_STRING_FORMAT_ERROR_CURLY_BRACE {
            get {
                return ResourceManager.GetString("PROP_STRING_FORMAT_ERROR_CURLY_BRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delimiter of property name is inaccurate..
        /// </summary>
        internal static string PROP_STRING_FORMAT_ERROR_DELIMITER_OF_PROPERTY_NAME {
            get {
                return ResourceManager.GetString("PROP_STRING_FORMAT_ERROR_DELIMITER_OF_PROPERTY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delimiter of property value is inaccurate..
        /// </summary>
        internal static string PROP_STRING_FORMAT_ERROR_DELIMITER_OF_PROPERTY_VALUE {
            get {
                return ResourceManager.GetString("PROP_STRING_FORMAT_ERROR_DELIMITER_OF_PROPERTY_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape character is inaccurate ({0})..
        /// </summary>
        internal static string PROP_STRING_FORMAT_ERROR_ESCAPE_CHARACTER {
            get {
                return ResourceManager.GetString("PROP_STRING_FORMAT_ERROR_ESCAPE_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name is empty..
        /// </summary>
        internal static string PROP_STRING_FORMAT_ERROR_PROPERTY_NAME_IS_EMPTY {
            get {
                return ResourceManager.GetString("PROP_STRING_FORMAT_ERROR_PROPERTY_NAME_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property value is empty..
        /// </summary>
        internal static string PROP_STRING_FORMAT_ERROR_PROPERTY_VALUE_IS_EMPTY {
            get {
                return ResourceManager.GetString("PROP_STRING_FORMAT_ERROR_PROPERTY_VALUE_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start character is inaccurate(=, ;, })..
        /// </summary>
        internal static string PROP_STRING_FORMAT_ERROR_START_CHARACTER {
            get {
                return ResourceManager.GetString("PROP_STRING_FORMAT_ERROR_START_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource file [{0}] was not found..
        /// </summary>
        internal static string RESOURCE_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESOURCE_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a switch by &quot;on&quot; or &quot;off&quot;. Config key:{0}.
        /// </summary>
        internal static string SWITCH_ERROR {
            get {
                return ResourceManager.GetString("SWITCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inaccurate tag is contained..
        /// </summary>
        internal static string THIS_DPQ_TAG_IS_UNKNOWN {
            get {
                return ResourceManager.GetString("THIS_DPQ_TAG_IS_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML declaration [{0}] is inaccurate..
        /// </summary>
        internal static string XML_DECLARATION_ERROR {
            get {
                return ResourceManager.GetString("XML_DECLARATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML element is inaccurate. {0}.
        /// </summary>
        internal static string XML_ELEMENT_ERROR {
            get {
                return ResourceManager.GetString("XML_ELEMENT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not log4net of a route element..
        /// </summary>
        internal static string XML_ELEMENT_ERROR_LOG4NET {
            get {
                return ResourceManager.GetString("XML_ELEMENT_ERROR_LOG4NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A setup of a password is required when enciphering..
        /// </summary>
        internal static string ZIP_PASSWORD {
            get {
                return ResourceManager.GetString("ZIP_PASSWORD", resourceCulture);
            }
        }
    }
}
