'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Aspx.Common

    Partial Public Class testScreen1

        '''<summary>
        '''Head1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''btnMButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMButton1 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

        '''<summary>
        '''lbnMLinkButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbnMLinkButton1 As Global.Touryo.Infrastructure.CustomControl.WebCustomLinkButton

        '''<summary>
        '''ibnMImageButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibnMImageButton1 As Global.Touryo.Infrastructure.CustomControl.WebCustomImageButton

        '''<summary>
        '''impMImageMap1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents impMImageMap1 As Global.Touryo.Infrastructure.CustomControl.WebCustomImageMap

        '''<summary>
        '''btnMButton2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMButton2 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

        '''<summary>
        '''lbnMLinkButton2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbnMLinkButton2 As Global.Touryo.Infrastructure.CustomControl.WebCustomLinkButton

        '''<summary>
        '''ibnMImageButton2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibnMImageButton2 As Global.Touryo.Infrastructure.CustomControl.WebCustomImageButton

        '''<summary>
        '''impMImageMap2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents impMImageMap2 As Global.Touryo.Infrastructure.CustomControl.WebCustomImageMap

        '''<summary>
        '''TextBox1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBox1 As Global.Touryo.Infrastructure.CustomControl.WebCustomTextBox

        '''<summary>
        '''btnMButton3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMButton3 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

        '''<summary>
        '''lbnMLinkButton3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbnMLinkButton3 As Global.Touryo.Infrastructure.CustomControl.WebCustomLinkButton

        '''<summary>
        '''ibnMImageButton3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibnMImageButton3 As Global.Touryo.Infrastructure.CustomControl.WebCustomImageButton

        '''<summary>
        '''CheckBox1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBox1 As Global.Touryo.Infrastructure.CustomControl.WebCustomCheckBox

        '''<summary>
        '''TextBox2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBox2 As Global.Touryo.Infrastructure.CustomControl.WebCustomTextBox

        '''<summary>
        '''TextBox3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBox3 As Global.Touryo.Infrastructure.CustomControl.WebCustomTextBox

        '''<summary>
        '''btnMButton4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMButton4 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

        '''<summary>
        '''lbnMLinkButton4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbnMLinkButton4 As Global.Touryo.Infrastructure.CustomControl.WebCustomLinkButton

        '''<summary>
        '''btnMButton21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMButton21 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

        '''<summary>
        '''lbnMLinkButton21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbnMLinkButton21 As Global.Touryo.Infrastructure.CustomControl.WebCustomLinkButton

        '''<summary>
        '''ibnMImageButton21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibnMImageButton21 As Global.Touryo.Infrastructure.CustomControl.WebCustomImageButton

        '''<summary>
        '''impMImageMap21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents impMImageMap21 As Global.Touryo.Infrastructure.CustomControl.WebCustomImageMap

        '''<summary>
        '''btnMButton22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMButton22 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

        '''<summary>
        '''lbnMLinkButton22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbnMLinkButton22 As Global.Touryo.Infrastructure.CustomControl.WebCustomLinkButton

        '''<summary>
        '''ibnMImageButton22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibnMImageButton22 As Global.Touryo.Infrastructure.CustomControl.WebCustomImageButton

        '''<summary>
        '''impMImageMap22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents impMImageMap22 As Global.Touryo.Infrastructure.CustomControl.WebCustomImageMap

        '''<summary>
        '''TextBox4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBox4 As Global.Touryo.Infrastructure.CustomControl.WebCustomTextBox

        '''<summary>
        '''btnMButton23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMButton23 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

        '''<summary>
        '''lbnMLinkButton23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbnMLinkButton23 As Global.Touryo.Infrastructure.CustomControl.WebCustomLinkButton

        '''<summary>
        '''ibnMImageButton23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibnMImageButton23 As Global.Touryo.Infrastructure.CustomControl.WebCustomImageButton

        '''<summary>
        '''CheckBox2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBox2 As Global.Touryo.Infrastructure.CustomControl.WebCustomCheckBox

        '''<summary>
        '''TextBox5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBox5 As Global.Touryo.Infrastructure.CustomControl.WebCustomTextBox

        '''<summary>
        '''TextBox6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBox6 As Global.Touryo.Infrastructure.CustomControl.WebCustomTextBox

        '''<summary>
        '''btnMButton24 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMButton24 As Global.Touryo.Infrastructure.CustomControl.WebCustomButton

        '''<summary>
        '''lbnMLinkButton24 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbnMLinkButton24 As Global.Touryo.Infrastructure.CustomControl.WebCustomLinkButton

        '''<summary>
        '''ibnMImageButton24 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibnMImageButton24 As Global.Touryo.Infrastructure.CustomControl.WebCustomImageButton

        '''<summary>
        '''impMImageMap24 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents impMImageMap24 As Global.Touryo.Infrastructure.CustomControl.WebCustomImageMap

        '''<summary>
        '''ContentPlaceHolder_A control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContentPlaceHolder_A As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''ContentPlaceHolder_B control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContentPlaceHolder_B As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''ContentPlaceHolder_C control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContentPlaceHolder_C As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''ChildScreenType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChildScreenType As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ChildScreenUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChildScreenUrl As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''CloseFlag control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CloseFlag As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''SubmitFlag control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubmitFlag As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ScreenGuid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScreenGuid As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''FxDialogStyle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FxDialogStyle As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''BusinessDialogStyle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BusinessDialogStyle As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''NormalScreenStyle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NormalScreenStyle As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''NormalScreenTarget control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NormalScreenTarget As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''DialogFrameUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DialogFrameUrl As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''WindowGuid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WindowGuid As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''RequestTicketGuid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequestTicketGuid As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
