//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeployZipPackWithHTTP.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeployZipPackWithHTTP.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   /HELP Show me the HELP. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0001 {
            get {
                return ResourceManager.GetString("A0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /CUI I will start in CUI CUI. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0002 {
            get {
                return ResourceManager.GetString("A0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Below, valid options argument only when CUI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0003 {
            get {
                return ResourceManager.GetString("A0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   / Force update to erase the FORCE history file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0004 {
            get {
                return ResourceManager.GetString("A0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /QUIET (Hide the message) that you can run in quiet mode . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0005 {
            get {
                return ResourceManager.GetString("A0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /SILENT (Hide message, the progress) that will run in silent mode. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0006 {
            get {
                return ResourceManager.GetString("A0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /NB Ignore start instruction assembly even if they are specified in the manifest file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0007 {
            get {
                return ResourceManager.GetString("A0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /WWWURL I Specifies the URL to the manifest file of  \ &quot;http://xxxx \&quot; WWW server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0008 {
            get {
                return ResourceManager.GetString("A0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /WWWUID xxxx WWW Specifies the user ID when accessing the server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0009 {
            get {
                return ResourceManager.GetString("A0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /WWWPWD xxxx WWW Specifies the password used to access the server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0010 {
            get {
                return ResourceManager.GetString("A0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /WWWDomain xxxx WWW You specify the domain when accessing to the server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0011 {
            get {
                return ResourceManager.GetString("A0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /ProxyURL \&quot;http://yyyy\&quot; Proxy I specify the URL to the server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0012 {
            get {
                return ResourceManager.GetString("A0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If it is not specified, and then apply the IE setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0013 {
            get {
                return ResourceManager.GetString("A0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It does not use a proxy [none] is specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0014 {
            get {
                return ResourceManager.GetString("A0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /ProxyUID yyyy Proxy Specifies the user ID when accessing the server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0015 {
            get {
                return ResourceManager.GetString("A0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /ProxyPWD yyyy Proxy Specifies the password used to access the server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0016 {
            get {
                return ResourceManager.GetString("A0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /ProxyDomain yyyy Proxy You specify the domain when accessing to the server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0017 {
            get {
                return ResourceManager.GetString("A0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /UnIns \&quot;http://xxxx\&quot; WWW Specify the URL to the manifest file on the server (uninstall). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A0018 {
            get {
                return ResourceManager.GetString("A0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Exception: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error0001 {
            get {
                return ResourceManager.GetString("Error0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summary (compression) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error0002 {
            get {
                return ResourceManager.GetString("Error0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summary (De) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error0003 {
            get {
                return ResourceManager.GetString("Error0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIP file |*.Zip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXT0001 {
            get {
                return ResourceManager.GetString("EXT0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Production start of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0001 {
            get {
                return ResourceManager.GetString("I0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write start of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0002 {
            get {
                return ResourceManager.GetString("I0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I wrote {0} / {1} bytes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0003 {
            get {
                return ResourceManager.GetString("I0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write end of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0004 {
            get {
                return ResourceManager.GetString("I0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing of entry for {1} (s) has (have) completed {0} or in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0005 {
            get {
                return ResourceManager.GetString("I0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creation end of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0006 {
            get {
                return ResourceManager.GetString("I0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0001 {
            get {
                return ResourceManager.GetString("M0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;Message&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0002 {
            get {
                return ResourceManager.GetString("M0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;Stack trace&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0003 {
            get {
                return ResourceManager.GetString("M0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;Internal exception&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0004 {
            get {
                return ResourceManager.GetString("M0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0005 {
            get {
                return ResourceManager.GetString("M0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CUI start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0006 {
            get {
                return ResourceManager.GetString("M0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GUI boot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0007 {
            get {
                return ResourceManager.GetString("M0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Exception: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0008 {
            get {
                return ResourceManager.GetString("M0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0009 {
            get {
                return ResourceManager.GetString("M0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not do anything with &apos;no&apos; overwrite with &apos;yes&apos; stop &apos;Cancel&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0010 {
            get {
                return ResourceManager.GetString("M0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overwrite Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0011 {
            get {
                return ResourceManager.GetString("M0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0012 {
            get {
                return ResourceManager.GetString("M0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start-up conditions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0013 {
            get {
                return ResourceManager.GetString("M0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0014 {
            get {
                return ResourceManager.GetString("M0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0015 {
            get {
                return ResourceManager.GetString("M0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successful completion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S0001 {
            get {
                return ResourceManager.GetString("S0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abnormal termination に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S0002 {
            get {
                return ResourceManager.GetString("S0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T0001 {
            get {
                return ResourceManager.GetString("T0001", resourceCulture);
            }
        }
    }
}
