SELECT * FROM ADMINISTRATOR.EMPLOYEE
WHERE
JOB = @JOB
AND COMM = @COMM1
AND EMPNO IN (SELECT EMPNO FROM ADMINISTRATOR.EMPLOYEE WHERE COMM = @COMM2)
AND SEX IN (@P1,@P2)
ORDER BY %COLUMN% %SEQUENCE%

/*PARAM*JOB,String,CLERK*PARAM*/
/*PARAM*COMM1,Decimal,2301.00*PARAM*/
/*PARAM*COMM2,Single,2301.00*PARAM*/
/*PARAM* P1, Char, M *PARAM*/
/*PARAM* P2, Char, F *PARAM*/
/*PARAM*COLUMN,EMPNO*PARAM*/
/*PARAM*SEQUENCE,DESC*PARAM*/

-- パラメタ設定済み
